### ISSUE TITLE
Java Error when running  -m update_one iterate_many

### ISSUE THREAD

**Issue by manjo-git** [idealo/mongodb-performance-test#4]
I first ran the following INSERT command 

`
java -jar $jarfile -m insert -o 1000000 -t 10 -db test -c perf -h 192.168.1.6 -port 27017
`

and then ran update_one iterate_many tests

`java -jar $jarfile -db test -c perf -h 192.168.1.6 -port 27017 -m update_one iterate_many -t 10 10 20 20 30 30`

and got the following error message scrolling through the screen. 

`
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2020-08-27 15:17:12,265 [pool-2-thread-2] ERROR d.i.m.perf.operations.IOperation - error while executing query on field '_id' with value '849735'
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:70) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:167) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:145) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:100) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:277) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:201) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1048) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1032) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:617) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:612) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.operations.UpdateOperation.executeQuery(UpdateOperation.java:25) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.operations.AbstractOperation.operation(AbstractOperation.java:74) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.OperationExecutor.doOperation(OperationExecutor.java:91) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.OperationExecutor.lambda$null$0(OperationExecutor.java:134) ~[mongodb-performance-test.jar:1.1.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2020-08-27 15:17:12,266 [pool-2-thread-5] ERROR d.i.m.perf.operations.IOperation - error while executing query on field '_id' with value '90905'
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:70) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:167) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:145) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:100) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:277) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:201) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1048) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1032) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:617) ~[mongodb-performance-test.jar:1.1.0]
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:612) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.operations.UpdateOperation.executeQuery(UpdateOperation.java:25) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.operations.AbstractOperation.operation(AbstractOperation.java:74) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.OperationExecutor.doOperation(OperationExecutor.java:91) ~[mongodb-performance-test.jar:1.1.0]
	at de.idealo.mongodb.perf.OperationExecutor.lambda$null$0(OperationExecutor.java:134) ~[mongodb-performance-test.jar:1.1.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2020-08-27 15:17:12,266 [pool-2-thread-8] ERROR d.i.m.perf.operations.IOperation - error while executing query on field '_id' with value '281101'
java.lang.IllegalStateException: state should be: open
`

**Comment by kagahd** [comment]
I'm sorry to answer so late - I didn't see your issue earlier.
I tried to reproduce the issue but all my tests ran successfully. 
Did you run other tasks or different tests concurrently on the same database (you should not - the database should be exclusively used by the test). Do you can reproduce the issue?

**Comment by kagahd** [comment]
Closed due to inactivity.
